[project]
name = "productivity-cli"
version = "0.1.0"
description = "Productivity suite CLI tool built in Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "rich>=14.1.0",
    "ruff>=0.13.2",
]
