name: UV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.22"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Enable caching
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Build project
        run: uv build  # or whatever UV build command you have
